name: open-telemetry-grafana

services:
  grafana:
    image: grafana/grafana:latest-ubuntu
    pull_policy: always
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - ./grafana-agent/grafana-agent.river:/etc/agent/config.river:ro
    pull_policy: always
    environment:
      - AGENT_MODE=flow
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/config.river
    ports:
      - "12345:12345"
      - 4317:4317
      - 4318:4318
    depends_on:
      - loki
      - tempo
      - prometheus

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml:ro
    pull_policy: always
    command:
      - '-config.file=/etc/loki/loki.yaml'
    ports:
      - 3100:3100

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    pull_policy: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    pull_policy: always
    command:
      - '-config.file=/etc/tempo.yaml'
    ports:
      - 3200:3200

volumes:
  grafana-data:
